export const defaultSites = [
  {
    "site_code": "AMD-GT-001",
    "city": "Ahmedabad",
    "area": "Shivranjani",
    "address": "Shivranjani Bridge- Nr.D Mart Junction - Left",
    "size": "30x10",
    "media_type": "Gantry",
    "lighting": "BL",
    "facing": "Left",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 250000,
    "monthly_rate": 250000,
    "gps": "23.019187, 72.530184",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-GT-002",
    "city": "Ahmedabad",
    "area": "Shivranjani",
    "address": "Shivranjani Bridge- Nr.D Mart Junction - Middel",
    "size": "30x10",
    "media_type": "Gantry",
    "lighting": "BL",
    "facing": "Middle",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 250000,
    "monthly_rate": 250000,
    "gps": "23.019187, 72.530184",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-GT-003",
    "city": "Ahmedabad",
    "area": "Shivranjani",
    "address": "Shivranjani Bridge- Nr.D Mart Junction - Right",
    "size": "30x10",
    "media_type": "Gantry",
    "lighting": "BL",
    "facing": "Right",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 250000,
    "monthly_rate": 250000,
    "gps": "23.019177, 72.530066",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-GT-004",
    "city": "Ahmedabad",
    "area": "Shivranjani",
    "address": "Shivranjani Bridge- Fcg. Shyamal 4 road Jnc - Left",
    "size": "30x10",
    "media_type": "Gantry",
    "lighting": "BL",
    "facing": "Left",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 225000,
    "monthly_rate": 225000,
    "gps": "23.018881, 72.530022",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-GT-005",
    "city": "Ahmedabad",
    "area": "Shivranjani",
    "address": "Shivranjani Bridge- Fcg. Shyamal 4 road Jnc - Middel",
    "size": "30x10",
    "media_type": "Gantry",
    "lighting": "BL",
    "facing": "Middle",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 225000,
    "monthly_rate": 225000,
    "gps": "23.018881, 72.530022",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-GT-006",
    "city": "Ahmedabad",
    "area": "Shivranjani",
    "address": "Shivranjani Bridge- Fcg. Shyamal 4 road Jnc - Right",
    "size": "30x10",
    "media_type": "Gantry",
    "lighting": "BL",
    "facing": "Right",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 225000,
    "monthly_rate": 225000,
    "gps": "23.018881, 72.530022",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-UP-001",
    "city": "Ahmedabad",
    "area": "Shivranjani",
    "address": "Outside Kalamandir Jewellers  Traffic from Nehrunagar Circle to Shivranjani Junction",
    "size": "20x20",
    "media_type": "Unipole",
    "lighting": "BL",
    "facing": "Single",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 350000,
    "monthly_rate": 350000,
    "gps": "23.023702, 72.533068",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-UP-002",
    "city": "Ahmedabad",
    "area": "Shivranjani",
    "address": "Shivranjani Junction  traffic from SG Road",
    "size": "14x14",
    "media_type": "Unipole",
    "lighting": "BL",
    "facing": "Single",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 250000,
    "monthly_rate": 250000,
    "gps": "23.024627, 72.529971",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-UP-003",
    "city": "Ahmedabad",
    "area": "Satellite",
    "address": "ISRO - Nr. Bhavnirjar Gat, Satellite Road, Iscon to Jodhpur Cross Road",
    "size": "20x10",
    "media_type": "Unipole",
    "lighting": "BL",
    "facing": "Single",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 250000,
    "monthly_rate": 250000,
    "gps": "23.028015, 72.519220",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-UP-004",
    "city": "Ahmedabad",
    "area": "Satellite",
    "address": "Satellite Road Opp. Sundarvan traffic from Isro to Jodhpur",
    "size": "15x15",
    "media_type": "Unipole",
    "lighting": "BL",
    "facing": "Single",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 225000,
    "monthly_rate": 225000,
    "gps": "23.027722, 72.521722",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-001",
    "city": "Ahmedabad",
    "area": "Sindhubhavan",
    "address": "Sindhubhavan Rd. Fcg.Sindhu Bhavan  To Pakvan Jnc - Upper",
    "size": "30x15",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Upper",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 250000,
    "monthly_rate": 250000,
    "gps": "23.030001, 72.527826",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-002",
    "city": "Ahmedabad",
    "area": "Sindhubhavan",
    "address": "Sindhubhavan Rd. Fcg.Sindhu Bhavan  To Pakvan Jnc - Lower",
    "size": "30x15",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Lower",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 250000,
    "monthly_rate": 250000,
    "gps": "23.030001, 72.527826",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-003",
    "city": "Ahmedabad",
    "area": "Bopal Ambli Road",
    "address": "Bopal Ambli Road – Fcg. Iscon to Bopal",
    "size": "20x10",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Facing",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 250000,
    "monthly_rate": 250000,
    "gps": "23.028710, 72.490397",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-004",
    "city": "Ahmedabad",
    "area": "Bopal Ambli Road",
    "address": "Bopal Ambli. Fcg from Iscon Circle to Bopal Ambli",
    "size": "14x14",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Facing",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 250000,
    "monthly_rate": 250000,
    "gps": "23.027264, 72.505747",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-005",
    "city": "Ahmedabad",
    "area": "Bopal Ambli Road",
    "address": "Zaveri Circle",
    "size": "31x15",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Single",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 325000,
    "monthly_rate": 325000,
    "gps": "23.018583, 72.494472",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-006",
    "city": "Ahmedabad",
    "area": "S.G.Highway",
    "address": "Karnavati Club Fcg Ring Road to SG Highway",
    "size": "24x12",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Facing",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 225000,
    "monthly_rate": 225000,
    "gps": "23.018839, 72.501663",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-007",
    "city": "Ahmedabad",
    "area": "S.G.Highway",
    "address": "Thaltej  junction outside PVR – Traffic from Sal  & Gurudwara - Upper",
    "size": "30x15",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Upper",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 225000,
    "monthly_rate": 225000,
    "gps": "23.050126, 72.516999",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-008",
    "city": "Ahmedabad",
    "area": "S.G.Highway",
    "address": "Thaltej  junction outside PVR – Traffic from Sal  & Gurudwara - Lower",
    "size": "30x15",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Lower",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 225000,
    "monthly_rate": 225000,
    "gps": "23.050126, 72.516999",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-009",
    "city": "Ahmedabad",
    "area": "S.G.Highway",
    "address": "Thaltej Acropolis Mall Thaltej Junction Fcg Sal Hospital",
    "size": "42x20",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Facing",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 400000,
    "monthly_rate": 400000,
    "gps": "23.049593, 72.516808",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-010",
    "city": "Ahmedabad",
    "area": "Vastrapur",
    "address": "Vastrapur Lake- Nr. Alpha One Mall",
    "size": "20x15",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Single",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 250000,
    "monthly_rate": 250000,
    "gps": "23.039800, 72.528029",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-011",
    "city": "Ahmedabad",
    "area": "Vastrapur",
    "address": "Vastrapur Junction",
    "size": "20x10",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Single",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 250000,
    "monthly_rate": 250000,
    "gps": "23.037570, 72.527889",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-012",
    "city": "Ahmedabad",
    "area": "Judgesbunglow",
    "address": "Sal Hospital Junction  - Traffic ftf Sal Hospital to Judges Bungalows",
    "size": "20x10",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Front-to-Front",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 225000,
    "monthly_rate": 225000,
    "gps": "23.048272, 72.523345",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-013",
    "city": "Ahmedabad",
    "area": "Judgesbunglow",
    "address": "Sal Hospital  Fcg Drivein to Thaltej",
    "size": "30x15",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Facing",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 275000,
    "monthly_rate": 275000,
    "gps": "23.048371, 72.523147",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-014",
    "city": "Ahmedabad",
    "area": "Judgesbunglow",
    "address": "Keshavbaug To Mansi Jnc.-Opposite ITC Narmada Hotel",
    "size": "20x31",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Single",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 275000,
    "monthly_rate": 275000,
    "gps": "23.030001, 72.527826",
    "notes": "",
    "flags": "[\"Height (31ft) exceeds width (20ft) — confirm this isn't a swapped W/H entry\"]"
  },
  {
    "site_code": "AMD-HD-015",
    "city": "Ahmedabad",
    "area": "Judgesbunglow",
    "address": "Keshav Baugh junction",
    "size": "20x15",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Single",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 300000,
    "monthly_rate": 300000,
    "gps": "23.028541, 72.531762",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-016",
    "city": "Ahmedabad",
    "area": "Satellite",
    "address": "Jodhpur Cr Road – Outside iconic Showroom",
    "size": "15x31",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Single",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 195000,
    "monthly_rate": 195000,
    "gps": "23.026120, 72.525703",
    "notes": "",
    "flags": "[\"Height (31ft) exceeds width (15ft) — confirm this isn't a swapped W/H entry\"]"
  },
  {
    "site_code": "AMD-HD-017",
    "city": "Ahmedabad",
    "area": "Prahladnagar",
    "address": "Prahladnagar Road – Towards Anandnagar - Upper (Sachin Tower)",
    "size": "30x15",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Upper",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 195000,
    "monthly_rate": 195000,
    "gps": "23.013021, 72.524427",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-018",
    "city": "Ahmedabad",
    "area": "Prahladnagar",
    "address": "Prahladnagar Road – Towards Anandnagar - Lower",
    "size": "30x15",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Lower",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 195000,
    "monthly_rate": 195000,
    "gps": "23.013021, 72.524427",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-019",
    "city": "Ahmedabad",
    "area": "Prahladnagar",
    "address": "Prahladnagar Road – Towards Shymal Cross Road Upper",
    "size": "15x15",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Upper",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 95000,
    "monthly_rate": 95000,
    "gps": "23.013523, 72.526682",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-020",
    "city": "Ahmedabad",
    "area": "Prahladnagar",
    "address": "Prahladnagar Road – Towards Shymal Cross Road Lower",
    "size": "15x15",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Lower",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 95000,
    "monthly_rate": 95000,
    "gps": "23.013523, 72.526682",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-021",
    "city": "Ahmedabad",
    "area": "Prahladnagar",
    "address": "Prahladnagar Road ftf Shyamal Cr Road to Anandnagar - Upper",
    "size": "15x15",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Front-to-Front",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 67500,
    "monthly_rate": 67500,
    "gps": "23.013523, 72.526682",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-022",
    "city": "Ahmedabad",
    "area": "Prahladnagar",
    "address": "Prahladnagar Road ftf Shyamal Cr Road to Anandnagar - Lower",
    "size": "15x15",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Front-to-Front",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 67500,
    "monthly_rate": 67500,
    "gps": "23.013523, 72.526682",
    "notes": "",
    "flags": "[\"Source row had no serial number\"]"
  },
  {
    "site_code": "AMD-HD-023",
    "city": "Ahmedabad",
    "area": "Science City",
    "address": "Science City Road- Nr. Trends Show Room",
    "size": "30x15",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Single",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 150000,
    "monthly_rate": 150000,
    "gps": "23.075289, 72.510669",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-024",
    "city": "Ahmedabad",
    "area": "Judgesbunglow",
    "address": "Sun- N- Step Club - Sattadhar Cr. Road To Sal Hospital - Upper",
    "size": "30x15",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Upper",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 150000,
    "monthly_rate": 150000,
    "gps": "23.061082, 72.530859",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-025",
    "city": "Ahmedabad",
    "area": "Judgesbunglow",
    "address": "Sun- N- Step Club - Sattadhar Cr. Road To Sal Hospital - Lower",
    "size": "30x15",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Lower",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 150000,
    "monthly_rate": 150000,
    "gps": "23.061082, 72.530859",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-026",
    "city": "Ahmedabad",
    "area": "Gota",
    "address": "Silver Cross Road Gota to Chandlodiya Overbridge",
    "size": "20x10",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Single",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 95000,
    "monthly_rate": 95000,
    "gps": "23.082665, 72.546350",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-027",
    "city": "Ahmedabad",
    "area": "Hebatpur",
    "address": "Hebatpur Road – Opp Columbia Asia Hospital",
    "size": "20x15",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Single",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 150000,
    "monthly_rate": 150000,
    "gps": "23.057543, 72.510842",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-028",
    "city": "Ahmedabad",
    "area": "Hebatpur",
    "address": "Hebatpur Road-Bagaban circle To Zydus Hospital",
    "size": "30x21",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Single",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 175000,
    "monthly_rate": 175000,
    "gps": "23.056085, 72.506030",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-029",
    "city": "Ahmedabad",
    "area": "Shahibaugh",
    "address": "Opp. Rajasthan Hospital towards Shahibaug Overbridge",
    "size": "14x14",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Single",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 110000,
    "monthly_rate": 110000,
    "gps": "23.052793, 72.595410",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-030",
    "city": "Ahmedabad",
    "area": "C.G Road",
    "address": "Ashram Road - Vallabh Sadan junction - Way to River Front",
    "size": "20x10",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Single",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 200000,
    "monthly_rate": 200000,
    "gps": "23.074490, 72.656098",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-031",
    "city": "Ahmedabad",
    "area": "C.G Road",
    "address": "Commerce College Road –Outside Wagh Bakri Tea Lounge - Upper",
    "size": "20x15",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Upper",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 85000,
    "monthly_rate": 85000,
    "gps": "23.033581, 72.555121",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-032",
    "city": "Ahmedabad",
    "area": "C.G Road",
    "address": "Commerce College Road –Outside Wagh Bakri Tea Lounge - Lower",
    "size": "20x15",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Lower",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 85000,
    "monthly_rate": 85000,
    "gps": "23.033581, 72.555121",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-033",
    "city": "Ahmedabad",
    "area": "SOBO",
    "address": "South Bopal -Opp Sobo Center Upper",
    "size": "30x15",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Upper",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 175000,
    "monthly_rate": 175000,
    "gps": "23.017947, 72.475671",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-034",
    "city": "Ahmedabad",
    "area": "SOBO",
    "address": "South Bopal -Opp Sobo Center Lower",
    "size": "30x15",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Lower",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 150000,
    "monthly_rate": 150000,
    "gps": "23.017947, 72.475671",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-035",
    "city": "Ahmedabad",
    "area": "200ft Ring Road",
    "address": "200ft Ring Road  Junction – From  YMCA Club Road to Club O7/South Bopal - Left - Upper",
    "size": "30x15",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Upper",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 150000,
    "monthly_rate": 150000,
    "gps": "23.009692, 72.478725",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-036",
    "city": "Ahmedabad",
    "area": "200ft Ring Road",
    "address": "200ft Ring Road  Junction – From  YMCA Club Road to Club O7/South Bopal - Left - Lower",
    "size": "30x15",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Lower",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 150000,
    "monthly_rate": 150000,
    "gps": "23.009692, 72.478725",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-037",
    "city": "Ahmedabad",
    "area": "200ft Ring Road",
    "address": "200ft Ring Road  Junction – From  YMCA Club Road to Club O7/South Bopal Right - Upper",
    "size": "30x15",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Upper",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 150000,
    "monthly_rate": 150000,
    "gps": "23.009692, 72.478725",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-038",
    "city": "Ahmedabad",
    "area": "200ft Ring Road",
    "address": "200ft Ring Road  Junction – From  YMCA Club Road to Club O7/South Bopal Right - Lower",
    "size": "30x15",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Lower",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 150000,
    "monthly_rate": 150000,
    "gps": "23.009692, 72.478725",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-039",
    "city": "Ahmedabad",
    "area": "Billionair Street",
    "address": "Billionaire Street Road- Nr.Karnavati Club Traffic from Bopal & Ring Road Upper",
    "size": "30x15",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Upper",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 150000,
    "monthly_rate": 150000,
    "gps": "23.018340, 72.493945",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-040",
    "city": "Ahmedabad",
    "area": "Billionair Street",
    "address": "Billionaire Street Road- Nr.Karnavati Club Traffic from Bopal & Ring Road Lower",
    "size": "30x15",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Lower",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 150000,
    "monthly_rate": 150000,
    "gps": "23.018340, 72.493945",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-041",
    "city": "Ahmedabad",
    "area": "Bopal",
    "address": "Bopal Road-  Nr. TRP Mall Upper (Aksardhara)",
    "size": "30x15",
    "media_type": "Hoarding",
    "lighting": "FL",
    "facing": "Upper",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 150000,
    "monthly_rate": 150000,
    "gps": "23.034310, 72.464996",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-042",
    "city": "Ahmedabad",
    "area": "Bopal",
    "address": "Bopal Road-  Nr. TRP Mall Lower (Aksardhara)",
    "size": "30x15",
    "media_type": "Hoarding",
    "lighting": "FL",
    "facing": "Lower",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 150000,
    "monthly_rate": 150000,
    "gps": "23.034310, 72.464996",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-043",
    "city": "Ahmedabad",
    "area": "Bopal",
    "address": "Bopal Road-  Nr. TRP Mall",
    "size": "41x15",
    "media_type": "Hoarding",
    "lighting": "FL",
    "facing": "Single",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 125000,
    "monthly_rate": 125000,
    "gps": "23.034156, 72.465140",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-044",
    "city": "Ahmedabad",
    "area": "Adani Shantigram",
    "address": "Opp. Adani Shantigram  Entry - Khoraj Fly Over",
    "size": "80x20",
    "media_type": "Hoarding",
    "lighting": "FL",
    "facing": "Single",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 325000,
    "monthly_rate": 325000,
    "gps": "23.145776, 72.546999",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-045",
    "city": "Ahmedabad",
    "area": "Bopal",
    "address": "Club O7 Road – Outside Skyville",
    "size": "30x27",
    "media_type": "Hoarding",
    "lighting": "BL",
    "facing": "Single",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 125000,
    "monthly_rate": 125000,
    "gps": "23.007130, 72.456622",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-046",
    "city": "Ahmedabad",
    "area": "Sanathal",
    "address": "Sanathal Circle  Bridge- Ahmedabad Entry from Changodar Upper",
    "size": "40x20",
    "media_type": "Hoarding",
    "lighting": "NL",
    "facing": "Upper",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 70000,
    "monthly_rate": 70000,
    "gps": "22.962323, 72.476140",
    "notes": "",
    "flags": "[]"
  },
  {
    "site_code": "AMD-HD-047",
    "city": "Ahmedabad",
    "area": "Sanathal",
    "address": "Sanathal Circle  Bridge- Ahmedabad Entry from Changodar Lower",
    "size": "40x20",
    "media_type": "Hoarding",
    "lighting": "NL",
    "facing": "Lower",
    "ownership": "",
    "availability": "Available",
    "vendor_name": "",
    "meter_no": "",
    "monthly_cost": 70000,
    "monthly_rate": 70000,
    "gps": "22.962323, 72.476140",
    "notes": "",
    "flags": "[]"
  }
];
export const defaultSettings = {
  "company_name": "Media Buzz",
  "default_city": "",
  "currency": "INR",
  "validation_interval": 15,
  "mounting_grace_days": 3,
  "electricity_due_soon_days": 7,
  "campaign_ending_warning_days": 7,
  "notification_emails": "",
  "email_notifications": 0,
  "proposal_validity": 7,
  "proposal_tax": 18,
  "proposal_terms": "Rates are exclusive of production/printing and mounting costs unless stated. 50% advance on confirmation, balance before mounting. Site availability is subject to confirmation in writing.",
  "delete_on_uninstall": 0
};
